

project: 
  type: website

website: 
  page-navigation: true

  title: "CIRES Lab Manual" 
 

  site-url: "https://ci-cmg.github.io/OceanAcoustics-LabManual/content/" 
  repo-url: "https://github.com/CI-CMG/OceanAcoustics-LabManual"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"

    logo: "https://upload.wikimedia.org/wikipedia/commons/1/1b/CIRES_logo.svg"

    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.ncei.noaa.gov/products/water-column-sonar-data
        text: "Water Column Sonar Data"
      - icon: globe
        href: https://www.ncei.noaa.gov/products/passive-acoustic-data
        text: "Passive Acoustic Data"

    style: "docked"
    search: true
    collapse-level: 1
    contents:

      - href: content/index.qmd
        text: Home
        contents:
          - href: content/index.qmd
            text: Introduction
          - href: content/index.qmd#overview-of-the-archives
            text: Overview of the Archives
                
      - href: content/first_day.qmd
        text: First Day Checklist
        
      - href: content/Onboarding.qmd
        text: New Employee Onboarding
      - href: content/Data Overview.qmd
        text: Overview Of Data We Work With
       
        
      - href: content/Archives.qmd
        text: Submitting Archive Data
        contents:
          - href: content/Archives.qmd#preparing-water-column-sonar-data-to-submit-to-the-archive
            text: Preparing Water Column Sonar Data to Submit to the Archive
          - href: content/Archives.qmd#preparing-passive-acoustic-data-to-submit-to-the-archive
            text: Preparing Passive Acoustic Data to Submit to the Archive
          - href: content/Archives.qmd#submitting-data-packages-to-the-archive
            text: Submitting Data Packages to the Archive
          
      - href: content/Accessing Data.qmd
        text: Guidance for Accessing Data

      - href: content/Pipeline.qmd
        text: Our Data Pipeline

      - href: content/Internal SOPs.qmd
        text: Internal SOPs
       
      
      - href: content/cheatsheet.qmd
        text: Cheat sheets
      - href: content/About.qmd
        text: Meet the team

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
