---
title: "Internal SOPs"
subtitle: "Standard Operating Procedures for Internal Use"
page-layout: full
---

Here on the Ocean Acoustics team we have written standard operating procedures (SOPs) to ingest data into the Water Column Sonar and the Passive Acoustic Data Archives. This information is not public and only NCEI employees will have access these Google docs.

In addition, NCEI-CO Marine Geology and Geophysics Section data managers created a shared SOP with general onboarding information and resources. This effort was guided heavily by the expertise of our very own Rory O'Flynn!

## NCEI-CO

-   For general information, see the [NCEI-CO General Onboarding SOP](https://docs.google.com/document/d/1hHp2uR01j5uc32sC1rGG0y60fZZk1YP7lyPGN2xeh6U/edit?tab=t.0)

-   For the centralized inter-team resource, see the [NCEI-CO Cheatsheet and Resource Masterlist](https://docs.google.com/document/d/11x_NaP7UQXSNS0E6dQMI5ReKUdW4pGkHMmQtdG0KIxE/edit?tab=t.0#heading=h.3j6g6sf8txl9)


## Water Column Sonar Data {#water-column-sonar-data}

### Internal Pipeline Procedures

-   Hard drives and datasets are logged in this spreadsheet: [WCSD Hard Drive & Dataset Tracking](https://docs.google.com/spreadsheets/d/1EhGSmuZTy8qifTNeYtcf2pe56KJDwlbLR0LU1qQYjjQ/edit?gid=1177595732#gid=1177595732)

-   Guidance on ingesting Water Column Sonar Data is documented in this SOP: [WCSD CPI Documentation](https://drive.google.com/open?id=1MyyPwDkDdgin1saL3C47ecqyRy1Dz5YOCRcK9wrPjB4&usp=drive_copy)

-   For information on handling WCSD data requests: [WCSD Data Delivery Procedure](https://drive.google.com/open?id=1LUsjjWfUPSWg2hc5v3Qcf1anT6QEoh38ib7DWDdLmz8&usp=drive_copy) 


## Passive Acoustic Data {#passive-acoustic-data}

### Internal Pipeline Procedures

-   For overall information on the ingest process of Passive Acoustic Data, take a look at this [Handbook for PAD Jr Data Managers](https://docs.google.com/document/d/1OMeRX3FjuKBY0EmbSw3D-PHH9TMMYfLyxP1rWEtNvbQ/edit?tab=t.8qnprcyu865#heading=h.k96d1lhgfln3) and [Handling of Drives: CheckSums, Pre-ingest and Ingest](https://drive.google.com/open?id=1be-xbYIlvfGrjZ6lDm_8G3vFHkGKlgS0PJpGR0tH9gE&usp=drive_copy)

-   Hard drives and datasets are tracked in this spreadsheet: [PAD Hard Drive & Dataset Tracking](https://docs.google.com/spreadsheets/d/1DAYFnoTvUCjtbLS3v35wgKleCMev0wB10JwVxbsS8vc/edit?usp=sharing)

-   For information on how to submit hard drive scanning tickets: [Handling of Drives: Scanning](https://docs.google.com/document/d/1atRfjl6khfhxhhEdReYFEJ0cfOirqKo8565qjtV4E-Y/edit?usp=sharing)

-   For the latest information on pre-ingest: [PAD Pre-Ingest 2.0](https://docs.google.com/document/d/1ZmELCT1uGybrPw83Ye4q079ws0_IsCNobLDvvapi-Gs/edit?usp=sharing)

-   For ingesting PAD [PAD Ingest SOP](https://docs.google.com/document/d/1-APUzbkyTKBXICk3wueSvLOlVGu3YwGbKxTVNwT-4bo/edit#heading=h.uy3n4wxjtta7)

-   For documenting errors: [PAD Errors and Issues](https://docs.google.com/document/d/13DEbLaEvLbh7V8Q2vY4i39D2fTG0bY8dO-qMqW8b9OI/edit?tab=t.0)

-   To track PAD data requests: [PAD Data Request and Delivery - Instructions](https://drive.google.com/open?id=1vGim7urIcylfPSga1h2PI-A2opnGV5y1ztaGTBlAzD0&usp=drive_copy)

## Software Development

### Data Packager Procedures

-   For documentation on PACE, the new PAD packaging tool PACE: [PACE Documentation](https://docs.google.com/document/d/186g-taroYaE5OtGgOa76aSvpDxN1Ek025jm5rpetgL0/edit?usp=sharing)

-   To create a new PACE release, follow the steps outlined in this [document](https://docs.google.com/document/d/1nq8g6xIVgzft-FzZzopiQnhvh76Yv5D2nrbJRuyUSbE/edit?tab=t.0). 

-   For info on creating a Windows signed version, view this [document](https://docs.google.com/document/d/1z0zqqlO9FYZhsqSZ_SZYW6KC3uew3xNfGdhgOgsrSeY/edit?tab=t.0)

### Internal Pipeline Procedures

-   For a general overview of Common Package Ingest (CPI) see this [folder](https://drive.google.com/drive/folders/1HR3kdociTIA1TmjCpRkOzj7Kt1U3RDhG?usp=sharing). 

-   Documentation of CPI can be found here: [CPI Overview](https://docs.google.com/document/d/1hMx30IeLQuNSGRxiAeGbq_gboVQ0NzrgsuvU_zwNhi8/edit?usp=drive_link)
